version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
